### ISSUE TITLE
imagededup cloning?

### ISSUE THREAD

**Issue by derwana** [MonkeyMaster64/Reddit-User-Media-Downloader-Public#3]
For the Linux Setup: why cloning `imagededup`, when it's already in the `requirements.txt`?

**Comment by derwana** [comment]
tested it, cloning is not necessary

**Comment by derwana** [comment]
#4

**Comment by dausruddin** [comment]
On Python 3.9.5, it spits out errors for Pillow 1.7.7 down to 1.0.

<kbd>![image](https://user-images.githubusercontent.com/5763466/119438268-61295a00-bd52-11eb-841a-af9632eb0ade.png)</kbd>

Then errors from numpy 1.6.2 down to 1.3.0

<kbd>![image](https://user-images.githubusercontent.com/5763466/119438644-43102980-bd53-11eb-8af3-1910f2f8aa2a.png)</kbd>

Then after super long wait, imagededup refused to install

<kbd>![image](https://user-images.githubusercontent.com/5763466/119440492-00505080-bd57-11eb-898f-827f538cc2fa.png)</kbd>

**Comment by MonkeyMaster64** [comment]
Approved the commits

**Comment by kdknigga** [comment]
> On Python 3.9.5, it spits out errors for Pillow 1.7.7 down to 1.0.
> ...

Yep, that's why I went with the newer imagededup that's not (yet?) in pypi.

**Comment by yoshijulas** [comment]
https://pillow.readthedocs.io/en/latest/installation.html#python-support

In python 3.9, Pillow only works version >= 8.0 and Imagededup requires <= 7

unless they update for the newer pillow, python 3.9 doesnt work

**Comment by dausruddin** [comment]
I'm wondering why @MonkeyMaster64 approved the commits without even considering.
